language: go

language: minimal

services:
  - docker

install:                                                                 
  - docker build . --network=host -t go-coap:build --target build

jobs:
  include:
    - stage: test
      if: type == pull_request
      script: 
        - docker run --network=host go-coap:build go test ./...

    - stage: test_and_cover
      if: type != pull_request
      script: 
        - >
            docker run
            --mount type=bind,source="$(pwd)",target=/shared
            --network=host
            go-coap:build
            go test ./... -covermode=atomic -coverprofile=/shared/coverage.txt
        - bash <(curl -s https://codecov.io/bash)
